services:
  database:
    image: postgres:13.12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ollcalamaison
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql
